openapi: 3.0.1
info:
  title: OrderPaymentServiceAPI
  description: API Definition of OrderPaymentServiceAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/orderpayment
paths:
  /:
    post:
      responses:
        default:
          description: Default response
