[package]
org = "thushani"
name = "customAddHeader"
version = "2.0.0"
export = ["customAddHeader"]
distribution = "2201.5.5"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow","choreo-apim-mediation-response-flow","choreo-apim-mediation-fault-flow"]

[build-options]
observabilityIncluded = true
