displayName: Vue Single Page Application
description: Simple Vue Single Page Web Application
componentType: web-application
buildPack: vue
repositoryUrl: https://github.com/wso2/choreo-samples/
componentPath: /vue-single-page-application
thumbnailPath: /icons/vue-single-page-application.svg
documentationPath: /vue-single-page-application/readme.md
imageVersion: 1.0.0
tags:
  - Vue
  - Single Page Application
